// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUu0QZzkjUlMK23eUDkWhXuEOYUsBk65o',
    appId: '1:152973280203:web:333f9c9a4807cd625a2c4e',
    messagingSenderId: '152973280203',
    projectId: 'tripscript-c8649',
    authDomain: 'tripscript-c8649.firebaseapp.com',
    storageBucket: 'tripscript-c8649.appspot.com',
    measurementId: 'G-P8N7KZ2FH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJdcOVy41CWsIuai2g4qWCdlRfs4quDxg',
    appId: '1:152973280203:android:43171cc1f359cccc5a2c4e',
    messagingSenderId: '152973280203',
    projectId: 'tripscript-c8649',
    storageBucket: 'tripscript-c8649.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgdNnNlaIrXA29xkDC7K0g7A_X_kUjpJA',
    appId: '1:152973280203:ios:31d540e993a213af5a2c4e',
    messagingSenderId: '152973280203',
    projectId: 'tripscript-c8649',
    storageBucket: 'tripscript-c8649.appspot.com',
    iosBundleId: 'com.example.tripScriptAdmin',
  );
}
